### ISSUE TITLE
Wtf? 

### ISSUE THREAD

**Issue by Serena-io** [asdfugil/Asdfugil.github.io#1]
Why do you keep a list of nicknames ive used before? https://github.com/asdfugil/Asdfugil.github.io/blob/master/dabezt.txt, this is super weird

**Comment by asdfugil** [comment]
Wdym https://github.com/asdfugil/Asdfugil.github.io/commit/fa62fd1403e5f7b6d29c10bfadee6a7397cf9736

**Comment by Serena-io** [comment]
?????????? Wtf

**Comment by Serena-io** [comment]
I didn’t even contribute and it showed I committed.. what the fuck

**Comment by Serena-io** [comment]
You are one creepy ass bitch
